name: scheduled-trigger

on:
#   schedule:
#     - cron: "*/5 * * * *" # every min
  workflow_dispatch:

jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Job 1"

 job2:
  runs-on: ubuntu-latest
  needs: job1
  steps:
  - run: echo "Job 2"
  - name: Wait 1 minute
    uses: jakejarvis/wait-action@master
    with:
      time: '1m'

 job3:
  runs-on: ubuntu-latest
  needs: job2
  steps:
    - run: echo "Job 3"
    - name: Wait 2 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '2m'
